site_name: 狼人杀Wiki
nav:
  - 首页: index.md
  - 笔记:
    - 笔记1: notes/note1.md
    - 笔记2: notes/note2.md
  - 关于: about.md
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: dark
  locale: zh_CN
repo_url: https://github.com/wutongxue132/langrenshawiki/
site_author: wutongxue132
copyright: 'Copyright © 2025 <a href="https://wutongxue132.pages.dev/">wutongxue132</a>'